services:
  db:
    image: postgres:16.4
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=unicorns
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile-crac
      args:
        - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://db:5432/unicorns
        - QUARKUS_DATASOURCE_USERNAME=postgres
        - QUARKUS_DATASOURCE_PASSWORD=postgres
    image: unicorn-store-quarkus-crack:latest
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://db:5432/unicorns
      - QUARKUS_DATASOURCE_USERNAME=postgres
      - QUARKUS_DATASOURCE_PASSWORD=postgres
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
